import { useEffect, useMemo, useRef, useState } from 'react'
import { supabase } from './lib/supabase.js'

const money = p => `£${(Number(p || 0) / 100000000).toFixed(1)}m`
const name = a => a.player_seasons?.players?.full_name || 'Player'
const position = a => a.player_seasons?.game_position || '—'
const left = date => {
  if (!date) return 'Starts after first bid'
  const seconds = Math.max(0, Math.floor((new Date(date) - Date.now()) / 1000))
  if (!seconds) return 'Ended'
  return seconds >= 3600 ? `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`
}

function AuthScreen() {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  async function auth(mode) {
    setBusy(true); setMessage('')
    const result = mode === 'signup' ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password })
    setMessage(result.error?.message || (mode === 'signup' ? 'Account created. Check your email if required.' : 'Signed in.')); setBusy(false)
  }
  return <div className="app-shell single-screen"><main><section className="hero-panel auth-panel"><div><span className="eyebrow">Manager account</span><h1>Enter Fantasy Football</h1><p>Build a club from unique player-season cards and compete across the history of English football.</p><div className="form-stack"><label>Email<input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" minLength="6" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label></div><div className="hero-actions"><button className="primary-btn" disabled={busy || !email || password.length < 6} onClick={() => auth('signin')}>{busy ? 'Please wait…' : 'Sign in'}</button><button className="secondary-btn" disabled={busy || !email || password.length < 6} onClick={() => auth('signup')}>Create account</button></div></div></section>{message && <div className="config-banner">{message}</div>}</main></div>
}

function ClubSetup({ onCreated }) {
  const [clubName, setClubName] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  async function createClub(e) { e.preventDefault(); setBusy(true); const { error } = await supabase.rpc('create_my_game_club', { p_name: clubName.trim() }); setMessage(error?.message || 'Club created — welcome to the Premier Division.'); setBusy(false); if (!error) await onCreated() }
  return <div className="app-shell single-screen"><main><section className="hero-panel auth-panel"><form onSubmit={createClub}><span className="eyebrow">Club creation</span><h1>Name your club</h1><p>This is the name other managers will see in auctions, fixtures and league tables.</p><div className="form-stack"><label>Club name<input required minLength="2" maxLength="40" value={clubName} onChange={e => setClubName(e.target.value)} placeholder="e.g. Gavin Athletic" /></label></div><button className="primary-btn" disabled={busy}>{busy ? 'Creating…' : 'Create club'}</button></form></section>{message && <div className="config-banner">{message}</div>}</main></div>
}

function AuctionCard({ auction: a, clubId, value, setValue, placeBid, busy, open, history, toggleHistory }) {
  const p = a.player_seasons, leading = a.current_winner_club_id === clubId, ended = a.status === 'ended' || (a.ends_at && new Date(a.ends_at) <= new Date())
  const minimum = a.current_winner_club_id ? Number(a.current_price_pence) + Number(a.min_increment_pence) : Number(a.reserve_price_pence)
  const invalid = value !== '' && Math.round(Number(value) * 100) < minimum
  return <article className={`auction-card${leading ? ' is-winning' : ''}${ended ? ' is-ended' : ''}`}><div className="player-head"><div className="avatar">{position(a)}</div><div className="player-copy"><span className="eyebrow">{leading ? '● You are winning' : ended ? 'Auction ended' : 'Day 1'}</span><h3>{name(a)}</h3><p>{p?.clubs?.name} · {position(a)} · Rating {p?.overall_rating || '—'}</p></div></div><div className="auction-price"><div><span>Current price</span><strong>{money(a.current_price_pence || a.reserve_price_pence)}</strong></div><small className={`timer${ended ? ' ended' : ''}`}>{left(a.ends_at)}</small></div><label className="bid-label">Your bid<input aria-label={`Bid for ${name(a)}`} type="number" step="10000" min={minimum / 100} disabled={ended || a.status !== 'live'} placeholder={`Minimum £${(minimum / 100).toLocaleString()}`} value={value} onChange={e => setValue(e.target.value)} /></label>{invalid && <small className="field-error">Minimum bid is {money(minimum)}</small>}<div className="hero-actions"><button className="primary-btn" disabled={busy || invalid || ended || a.status !== 'live'} onClick={placeBid}>{busy ? 'Placing…' : a.status === 'live' && !ended ? 'Place bid' : ended ? 'Auction ended' : 'Not live yet'}</button><button className="secondary-btn" onClick={toggleHistory}>{open ? 'Hide history' : 'Bid history'}</button></div>{open && <div className="bid-history"><strong>Recent bids</strong>{history.length ? history.slice(0, 6).map((h, i) => <div key={`${h.created_at || i}-${h.amount_pence}`}><span>{h.is_my_bid ? 'Your bid' : h.bid_type === 'ai' ? 'AI manager' : 'Other manager'}{h.is_current_winner ? ' · leading' : ''}</span><b>{money(h.amount_pence)}</b></div>) : <p>No bids yet.</p>}</div>}</article>
}

export default function App() {
  const [session, setSession] = useState(null), [authReady, setAuthReady] = useState(false), [state, setState] = useState(null), [auctions, setAuctions] = useState([]), [loading, setLoading] = useState(true), [message, setMessage] = useState(''), [bid, setBid] = useState({}), [bidding, setBidding] = useState(null), [tick, setTick] = useState(0), [selected, setSelected] = useState(null), [history, setHistory] = useState([]), [query, setQuery] = useState(''), [positionFilter, setPositionFilter] = useState('ALL'), [show, setShow] = useState('all')
  const selectedRef = useRef(null), clubRef = useRef(null)
  useEffect(() => { selectedRef.current = selected }, [selected]); useEffect(() => { clubRef.current = state?.club || null }, [state?.club])
  async function refresh(activeSession = session) {
    setLoading(true); const { data, error } = await supabase.rpc(activeSession ? 'get_my_game_state' : 'get_public_season_state'); if (error) setMessage(error.message); setState(data)
    if (activeSession) { const { data: items, error: auctionError } = await supabase.from('auctions').select('id,stage,status,reserve_price_pence,current_price_pence,current_winner_club_id,ends_at,min_increment_pence,player_seasons!inner(game_position,overall_rating,players!inner(full_name),clubs!inner(name))').eq('stage', 1).in('status', ['scheduled', 'live']).order('current_price_pence', { ascending: false }).limit(100); if (auctionError) setMessage(auctionError.message); setAuctions(items || []) }
    setLoading(false)
  }
  async function loadHistory(id, force = false) { if (!force && selectedRef.current === id) { setSelected(null); setHistory([]); return } setSelected(id); const { data, error } = await supabase.rpc('get_auction_bid_history', { p_auction_id: id }); if (error) setMessage(error.message); setHistory(data || []) }
  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => { setSession(data.session); setAuthReady(true); refresh(data.session) })
    const { data: listener } = supabase.auth.onAuthStateChange((_e, next) => { setSession(next); setTimeout(() => refresh(next), 0) })
    const timer = setInterval(() => setTick(x => x + 1), 1000)
    const channel = supabase.channel('auction-room').on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'auctions' }, payload => { setAuctions(old => old.map(a => a.id === payload.new.id ? { ...a, ...payload.new } : a).filter(a => ['scheduled', 'live'].includes(a.status))); const clubId = clubRef.current?.id; if (clubId && (payload.old.current_winner_club_id === clubId || payload.new.current_winner_club_id === clubId)) setTimeout(() => refresh(true), 0); if (selectedRef.current === payload.new.id) setTimeout(() => loadHistory(payload.new.id, true), 0) }).subscribe()
    return () => { listener.subscription.unsubscribe(); clearInterval(timer); supabase.removeChannel(channel) }
  }, [])
  async function placeBid(a) { const minimum = a.current_winner_club_id ? Number(a.current_price_pence) + Number(a.min_increment_pence) : Number(a.reserve_price_pence), amount = bid[a.id] === undefined || bid[a.id] === '' ? minimum : Math.round(Number(bid[a.id]) * 100); setBidding(a.id); setMessage(''); const { error } = await supabase.rpc('place_my_auction_bid', { p_auction_id: a.id, p_amount_pence: amount }); setMessage(error?.message || `Bid of ${money(amount)} placed on ${name(a)}.`); if (!error) { setBid(current => ({ ...current, [a.id]: '' })); await refresh(true); if (selected === a.id) await loadHistory(a.id, true) } setBidding(null) }
  const visible = useMemo(() => auctions.filter(a => { const q = query.trim().toLowerCase(); return (!q || name(a).toLowerCase().includes(q) || (a.player_seasons?.clubs?.name || '').toLowerCase().includes(q)) && (positionFilter === 'ALL' || position(a) === positionFilter) && (show === 'all' || show === 'winning' && a.current_winner_club_id === state?.club?.id || show === 'live' && a.status === 'live') }), [auctions, query, positionFilter, show, state?.club?.id, tick])
  if (!authReady) return <div className="loading-screen">Loading Fantasy Football…</div>
  if (!session) return <AuthScreen />
  if (loading && !state) return <div className="loading-screen">Loading your club…</div>
  if (!state?.club) return <ClubSetup onCreated={() => refresh(true)} />
  const { season, club } = state, available = Number(club.budget_pence || 0) - Number(club.reserved_pence || 0), winning = auctions.filter(a => a.current_winner_club_id === club.id).length
  return <div className="app-shell single-screen"><main><header className="topbar"><div><span className="eyebrow">Premier Division · {season?.name || 'Season 1'}</span><h1>{club.name}</h1><p>Day 1 auction room · prices and bid history update live</p></div><button className="ghost-btn" onClick={() => supabase.auth.signOut()}>Sign out</button></header><section className="stats-grid"><div className="stat-card"><div><span>Budget</span><strong>{money(club.budget_pence)}</strong></div></div><div className="stat-card"><div><span>Available</span><strong>{money(available)}</strong><small>{money(club.reserved_pence)} committed</small></div></div><div className="stat-card"><div><span>Winning bids</span><strong>{winning}</strong><small>Across current auctions</small></div></div><div className="stat-card"><div><span>Day 1 cards</span><strong>{auctions.length}</strong><small>Prices update live</small></div></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">Player market</span><h2>Live auctions</h2></div><span className="results-count">{visible.length} player{visible.length === 1 ? '' : 's'}</span></div><div className="auction-toolbar"><input type="search" placeholder="Search player or historical club" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Filter by position" value={positionFilter} onChange={e => setPositionFilter(e.target.value)}><option value="ALL">All positions</option>{['GK', 'DEF', 'MID', 'FWD'].map(item => <option key={item}>{item}</option>)}</select><div className="segmented"><button className={show === 'all' ? 'active' : ''} onClick={() => setShow('all')}>All</button><button className={show === 'live' ? 'active' : ''} onClick={() => setShow('live')}>Live</button><button className={show === 'winning' ? 'active' : ''} onClick={() => setShow('winning')}>Winning</button></div></div>{loading ? <div className="empty-state">Refreshing auctions…</div> : visible.length ? <div className="auction-grid">{visible.map(a => <AuctionCard key={a.id} auction={a} clubId={club.id} value={bid[a.id] ?? ''} setValue={value => setBid(current => ({ ...current, [a.id]: value }))} placeBid={() => placeBid(a)} busy={bidding === a.id} open={selected === a.id} history={history} toggleHistory={() => loadHistory(a.id)} />)}</div> : <div className="empty-state"><strong>No auctions match those filters.</strong><span>Try viewing all positions or clearing your search.</span></div>}</section>{message && <div className="config-banner toast" role="status"><span>{message}</span><button onClick={() => setMessage('')} aria-label="Dismiss message">×</button></div>}</main></div>
}
