import { useEffect, useState } from 'react'
import { BadgePoundSterling, CalendarDays, ChevronRight, CircleDollarSign, Clock3, Shield, Trophy, Users } from 'lucide-react'
import { supabase } from './lib/supabase.js'

const money = (p=0)=>`£${(Number(p)/100000000).toFixed(1)}m`
function Stat({icon:Icon,label,value,sub}){return <div className="stat-card"><div className="stat-icon"><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}

export default function App(){
 const [session,setSession]=useState(null),[state,setState]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[clubName,setClubName]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 async function load(s=session){
   const {data:pub}=await supabase.rpc('get_public_season_state');
   let mine=null;if(s){const {data}=await supabase.rpc('get_my_game_state');mine=data}
   setState({...pub,...mine})
 }
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);load(data.session)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);setTimeout(()=>load(s),0)});return()=>l.subscription.unsubscribe()},[])
 async function auth(mode){setBusy(true);setMsg('');const fn=mode==='signup'?supabase.auth.signUp({email,password}):supabase.auth.signInWithPassword({email,password});const {error}=await fn;if(error)setMsg(error.message);else if(mode==='signup')setMsg('Account created. Check your email if confirmation is enabled.');setBusy(false)}
 async function createClub(){setBusy(true);setMsg('');const {error}=await supabase.rpc('create_my_game_club',{p_name:clubName});if(error)setMsg(error.message);else{setMsg('Club created — welcome to the Premier Division.');await load(session)}setBusy(false)}
 const season=state?.season,club=state?.club,members=Number(state?.premier_members??19)
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">FF</div><div><strong>Fantasy Football</strong><span>Own history. Build a dynasty.</span></div></div><nav><a className="active"><Trophy size={18}/> Dashboard</a><a><CircleDollarSign size={18}/> Auctions</a><a><Users size={18}/> Squad</a><a><CalendarDays size={18}/> Fixtures</a><a><Shield size={18}/> League</a></nav></aside><main><header className="topbar"><div><span className="eyebrow">Premier Division · {season?.name||'Season 1'}</span><h1>{club?club.name:'Build your club'}</h1><p>{club?'Your dynasty starts here.':'Create an account, claim the final Premier Division place and enter the auction.'}</p></div>{session&&<button className="ghost-btn" onClick={()=>supabase.auth.signOut()}>Sign out</button>}</header>
 <section className="stats-grid"><Stat icon={BadgePoundSterling} label="Budget" value={money(club?.budget_pence??10000000000)} sub="17-player squad"/><Stat icon={Users} label="League places" value={`${club?20:members} / 20`} sub={club?'Premier Division member':'One human place reserved'}/><Stat icon={Clock3} label="Season" value={season?.status||'Scheduled'} sub="28-day cycle"/><Stat icon={CircleDollarSign} label="Player cards" value="537" sub="Unique 2025/26 cards"/></section>
 {!session?<section className="hero-panel"><div><span className="eyebrow">Manager account</span><h2>Sign in or create your account</h2><p>Your account permanently owns your fantasy club and player cards.</p><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><div className="hero-actions"><button disabled={busy} className="primary-btn" onClick={()=>auth('login')}>Sign in <ChevronRight size={18}/></button><button disabled={busy} className="secondary-btn" onClick={()=>auth('signup')}>Create account</button></div>{msg&&<p>{msg}</p>}</div></section>:!club?<section className="hero-panel"><div><span className="eyebrow">Final Premier Division place</span><h2>Name your club</h2><p>You start with £100m. Club names can be 2–40 characters.</p><input placeholder="Club name" maxLength="40" value={clubName} onChange={e=>setClubName(e.target.value)}/><div className="hero-actions"><button disabled={busy||clubName.trim().length<2} className="primary-btn" onClick={createClub}>Create club <ChevronRight size={18}/></button></div>{msg&&<p>{msg}</p>}</div></section>:<section className="hero-panel"><div><span className="eyebrow">Club created</span><h2>Welcome to the Premier Division, {club.name}.</h2><p>Your £100m budget is ready. Next we open the real Day 1 auction room and bidding.</p><button className="primary-btn">Enter Day 1 auction <ChevronRight size={18}/></button></div></section>}
 </main></div>}
