import { supabase } from './lib/supabase.js'
const fmt=d=>new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(d));let modal
const eventText=e=>`${e.minute}′ ${String(e.event_type||'event').replaceAll('_',' ')}${e.player_name?` · ${e.player_name}`:''}`
const initials=(n='')=>n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';const ratingClass=v=>Number(v||0)>=85?'elite':Number(v||0)>=78?'good':Number(v||0)>=70?'average':'low'
function formation(players){const s=(players||[]).filter(p=>p.slot_type==='starter'),c={CD:0,MD:0,ATT:0};s.forEach(p=>{if(c[p.game_position]!==undefined)c[p.game_position]++});return `${c.CD}-${c.MD}-${c.ATT}`}
function pitchPlayer(p,pos,i,n){const r=Math.round(Number(p.overall_rating||0));return `<div class="pitch-player pos-${pos.toLowerCase()} pos-${i+1}-of-${n}"><span class="pitch-rating ${ratingClass(r)}">${r}</span><span class="pitch-avatar">${initials(p.player_name)}</span><strong title="${p.player_name||''}">${p.player_name||'Unknown player'}</strong><span class="pitch-meta"><small>${p.game_position||''}</small><small>${p.season_label||''}</small></span></div>`}
function pitchHalf(players,side){const g={GK:[],CD:[],MD:[],ATT:[]};(players||[]).filter(p=>p.slot_type==='starter').forEach(p=>(g[p.game_position]||g.MD).push(p));return `<div class="formation-grid ${side}-formation">${['GK','CD','MD','ATT'].map(pos=>g[pos].map((p,i)=>pitchPlayer(p,pos,i,g[pos].length)).join('')).join('')}</div>`}
function benchRows(players){const r=(players||[]).filter(p=>p.slot_type==='bench');return r.length?r.map(p=>`<div class="bench-player"><span class="league-pos">${p.game_position||'—'}</span><div><strong>${p.player_name}</strong><small>${p.season_label||''}</small></div><b class="bench-rating ${ratingClass(p.overall_rating)}">${Math.round(Number(p.overall_rating||0))}</b></div>`).join(''):'<p class="league-lineup-empty">No substitutes available.</p>'}
function lineupPitch(h,a){return `<div class="matchday-lineup"><div class="pitch-team-head home-head"><strong>${h.name}</strong><span>${formation(h.players)}</span></div><div class="lineup-pitch"><div class="pitch-markings"><i class="centre-line"></i><i class="centre-circle"></i><i class="box top-box"></i><i class="box bottom-box"></i></div>${pitchHalf(h.players,'home')}${pitchHalf(a.players,'away')}</div><div class="pitch-team-head away-head"><strong>${a.name}</strong><span>${formation(a.players)}</span></div><div class="bench-heading">Substitutes</div><div class="league-benches"><section><h4>${h.name}</h4>${benchRows(h.players)}</section><section><h4>${a.name}</h4>${benchRows(a.players)}</section></div></div>`}
async function loadLineups(id,c){c.innerHTML='<p>Loading lineups…</p>';const {data,error}=await supabase.rpc('get_league_fixture_lineups',{p_fixture_id:id});c.innerHTML=error?`<p>${error.message}</p>`:lineupPitch(data.home_club,data.away_club)}
const pct=(a,b)=>a?`${Math.round(100*b/a)}%`:'0%';const row=(label,h,a)=>`<div class="detail-stat-row"><b>${h??0}</b><span>${label}</span><b>${a??0}</b></div>`
function detailedStats(d){if(!d?.team)return '<p>Detailed statistics are available for Match Engine 2.0 fixtures.</p>';const h=d.team.home,a=d.team.away;return `<div class="detailed-stats"><h3>Top stats</h3>${row('Possession',`${h.possession}%`,`${a.possession}%`)}${row('Expected goals (xG)',h.xg,a.xg)}${row('Total shots',h.shots,a.shots)}${row('Shots on target',h.shots_on_target,a.shots_on_target)}${row('Blocked shots',h.shots_blocked,a.shots_blocked)}${row('Big chances',h.big_chances,a.big_chances)}${row('Touches in opposition box',h.touches_box,a.touches_box)}${row('Corners',h.corners,a.corners)}<h3>Passing</h3>${row('Total passes',h.passes_attempted,a.passes_attempted)}${row('Pass accuracy',pct(h.passes_attempted,h.passes_completed),pct(a.passes_attempted,a.passes_completed))}<h3>Defence</h3>${row('Tackles',h.tackles,a.tackles)}${row('Interceptions',h.interceptions,a.interceptions)}${row('Blocks',h.blocks,a.blocks)}${row('Clearances',h.clearances,a.clearances)}<h3>Duels & discipline</h3>${row('Duels won',h.duels_won,a.duels_won)}${row('Duels lost',h.duels_lost,a.duels_lost)}${row('Fouls',h.fouls,a.fouls)}${row('Offsides',h.offsides,a.offsides)}${row('Yellow cards',h.yellow,a.yellow)}${row('Red cards',h.red,a.red)}</div>`}
function playerTable(team){return `<section class="player-match-team"><h3>${team.name}</h3><div class="player-stat-scroll"><table><thead><tr><th>Player</th><th>Min</th><th>Rat</th><th>G</th><th>A</th><th>Sh</th><th>xG</th><th>Pass</th><th>Tkl</th><th>Int</th></tr></thead><tbody>${(team.players||[]).map(p=>`<tr><td><b>${p.name}</b><small>${p.position}</small></td><td>${p.minutes}</td><td><strong>${Number(p.rating||0).toFixed(1)}</strong></td><td>${p.goals}</td><td>${p.assists}</td><td>${p.shots}</td><td>${Number(p.xg||0).toFixed(2)}</td><td>${p.passes_completed}/${p.passes_attempted}</td><td>${p.tackles}</td><td>${p.interceptions}</td></tr>`).join('')}</tbody></table></div></section>`}
async function loadStats(id,c,players=false){c.innerHTML='<p>Loading match statistics…</p>';const {data,error}=await supabase.rpc('get_league_match_statistics',{p_fixture_id:id});c.innerHTML=error?`<p>${error.message}</p>`:players?playerTable(data.home)+playerTable(data.away):detailedStats(data)}
const list=(xs,cls='')=>`<ul class="coach-list ${cls}">${(xs||[]).map(x=>`<li>${x}</li>`).join('')}</ul>`
function coachReport(d){const next=d.next_fixture;return `<div class="assistant-coach-report"><div class="coach-head"><span class="coach-avatar">AC</span><div><small>ASSISTANT COACH</small><h3>Post-match debrief</h3></div></div><p class="coach-verdict">${d.verdict}</p><p>${d.summary}</p><div class="coach-section positive"><h4>What worked</h4>${list(d.strengths)}</div><div class="coach-section warning"><h4>Problems identified</h4>${list(d.problems)}</div><div class="coach-section advice"><h4>Advice for the next match</h4>${list(d.recommendations)}</div>${d.player_notes?.length?`<div class="coach-section"><h4>Player notes</h4>${d.player_notes.map(n=>`<div class="coach-player-note"><b>${n.player}</b><span>${n.text}</span></div>`).join('')}</div>`:''}${next?`<div class="coach-next"><small>NEXT OPPONENT</small><strong>${next.opponent}</strong><span>${next.venue==='home'?'Home':'Away'} · ${fmt(next.scheduled_at)}</span></div>`:''}</div>`}
async function loadCoach(id,c){c.innerHTML='<p>Assistant coach is reviewing the match…</p>';const {data,error}=await supabase.rpc('get_assistant_coach_report',{p_fixture_id:id});c.innerHTML=error?`<p>${error.message}</p>`:coachReport(data)}
async function openCentre(id){ensureModal();const {data,error}=await supabase.rpc('get_league_match_centre',{p_fixture_id:id});if(error)return alert(error.message);const f=data.fixture,s=data.simulation,ev=data.events||[];const own=(await supabase.rpc('get_my_fixtures')).data?.some(x=>x.id===id);modal.querySelector('.league-browser-body').innerHTML=`<button class="league-back">← All matches</button><div class="league-centre"><small>${data.is_live?`LIVE · ${data.live_minute}′`:s?'FULL TIME':'UPCOMING'} · ROUND ${f.round_number}</small><h2>${f.home_club_name} <b>${s?`${s.home_goals} – ${s.away_goals}`:'–'}</b> ${f.away_club_name}</h2><div class="league-centre-tabs"><button class="active" data-tab="match">Match</button><button data-tab="stats">Stats</button><button data-tab="players">Players</button><button data-tab="lineups">Lineups</button>${own&&!data.is_live&&s?'<button data-tab="coach">Coach</button>':''}</div><div class="league-tab-panel" data-panel="match">${s?`<div class="league-stats">${row('Possession',`${s.home_possession}%`,`${s.away_possession}%`)}${row('Shots',s.home_shots,s.away_shots)}${row('On target',s.home_shots_on_target,s.away_shots_on_target)}${row('xG',s.home_xg,s.away_xg)}${row('Fouls',s.home_fouls,s.away_fouls)}</div>`:'<p>This match has not kicked off yet.</p>'}<h3>Match timeline</h3><div class="league-events">${ev.length?ev.map(e=>`<div>${eventText(e)}</div>`).join(''):'<p>No events to show.</p>'}</div></div><div class="league-tab-panel" data-panel="stats" hidden></div><div class="league-tab-panel" data-panel="players" hidden></div><div class="league-tab-panel" data-panel="lineups" hidden></div>${own?'<div class="league-tab-panel" data-panel="coach" hidden></div>':''}</div>`;modal.querySelector('.league-back').onclick=loadMatches;const tabs=[...modal.querySelectorAll('.league-centre-tabs button')];tabs.forEach(btn=>btn.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===btn));modal.querySelectorAll('.league-tab-panel').forEach(p=>p.hidden=p.dataset.panel!==btn.dataset.tab);const panel=modal.querySelector(`[data-panel="${btn.dataset.tab}"]`);if(!panel.dataset.loaded&&btn.dataset.tab!=='match'){panel.dataset.loaded='1';if(btn.dataset.tab==='lineups')loadLineups(id,panel);else if(btn.dataset.tab==='coach')loadCoach(id,panel);else loadStats(id,panel,btn.dataset.tab==='players')}})}
async function loadMatches(){ensureModal();const body=modal.querySelector('.league-browser-body');body.innerHTML='<p>Loading league matches…</p>';const {data,error}=await supabase.rpc('get_my_league_fixtures');if(error){body.innerHTML=`<p>${error.message}</p>`;return}const groups=(data||[]).reduce((a,f)=>((a[f.round_number]??=[]).push(f),a),{});body.innerHTML=Object.entries(groups).map(([round,fs])=>`<section class="league-round"><h3>Round ${round}</h3>${fs.map(f=>`<button class="league-game${f.is_my_match?' mine':''}" data-id="${f.id}"><span>${fmt(f.scheduled_at)}</span><strong>${f.home_club_name}</strong><b>${f.is_live?'LIVE':f.home_goals==null?'v':`${f.home_goals} – ${f.away_goals}`}</b><strong>${f.away_club_name}</strong><em>${f.is_live?'Watch live':f.home_goals==null?'Upcoming':'Match report'} →</em></button>`).join('')}</section>`).join('');body.querySelectorAll('.league-game').forEach(b=>b.onclick=()=>openCentre(b.dataset.id))}
function ensureModal(){if(!modal){modal=document.createElement('div');modal.className='league-browser-backdrop';modal.innerHTML='<div class="league-browser"><button class="league-browser-close">×</button><header><small>PREMIER DIVISION</small><h2>League Matches</h2><p>Every fixture, live match and result.</p></header><div class="league-browser-body"></div></div>';modal.querySelector('.league-browser-close').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()})}if(!modal.isConnected)document.body.append(modal);return modal}
function openBrowser(){ensureModal();loadMatches()}
window.addEventListener('fantasy:open-match-centre',e=>{const id=e.detail?.fixtureId;if(id)openCentre(id)})
function install(){const nav=document.querySelector('.side-nav, nav');if(!nav||nav.querySelector('.all-league-matches-btn'))return;const b=document.createElement('button');b.className='all-league-matches-btn';b.textContent='League Matches';b.onclick=openBrowser;nav.append(b)}new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});install();